# 回测配置文件
# 用户可以直接修改这个文件中的参数来调整回测设置

# ==================== 基本参数 ====================
# 信号文件名
signal_file: "pred5days_top2k"
  
# 信号目录(需要包含信号文件)
data_dir: "/Users/didi/DATA/dnn_model/signal"

# 数据缓存目录（包含vwap、combo_mask、trading_days、benchmark）
cache_dir: "/Users/didi/DATA/dnn_model/cache"
 
# ==================== 策略参数 ====================
# 每日截面选股数量
rank_n: 30

# 组合数量（资金分割份数）
portfolio_count: 5

# 调仓频率(daily/weekly/monthly)
rebalance_frequency: 'daily'

# ==================== 输出设置 ====================
# 净值曲线，回测结果将保存到该目录下，如果为空字符串，则不保存
output_dir: ""

